### PR TITLE
Adjust code execution order

### PR DESCRIPTION
**Pull request by elitecodegroovy**
Just Do adjust code execution order and make sure the code look more elegant.

### CODE REVIEW

**Comment by harshavardhana** [comment]
What is the issue that this code fixes? @elitecodegroovy

**Comment by elitecodegroovy** [comment]
> What is the issue that this code fixes? @elitecodegroovy

Nothing. I just adjusted the code execution order and make sure the code style is more elegant according to the standard of Golang style.

**Comment by harshavardhana** [comment]
> Nothing. I just adjusted the code execution order and make sure the code style is more elegant according to the standard of Golang style.

Have you tested the re-ordering?

**Comment by harshavardhana** [comment]
> > Nothing. I just adjusted the code execution order and make sure the code style is more elegant according to the standard of Golang style.
> 
> Have you tested the re-ordering?

too old of a PR closing with no activity.

**Pull request closed without merging**
